if (NOT CMAKE_COMPILER_IS_GNUCXX)
    message( FATAL_ERROR "This project only for GCC compiler!" )
endif()

if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS "8.3.0")
    message( FATAL_ERROR "This project only for GCC minimum version 8.3. Your version is ${CMAKE_CXX_COMPILER_VERSION}" )
endif()

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(SOFT_DEVELOPER "PeeceKeeper42")
set(DEVELOPER_DOMAIN "github.com/PeeceKeeper42")
set(ROOT_PROJECT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/..)
#set(RESOURCES_DIR ${ROOT_PROJECT_DIR}/_resources)
#set(COMMON_SOURCES_DIR ${ROOT_PROJECT_DIR}/_include)

if (${CMAKE_SIZEOF_VOID_P} STREQUAL 4)
    set(DIR_PREFIX "x86")
elseif (${CMAKE_SIZEOF_VOID_P} STREQUAL 8)
    set(DIR_PREFIX "x64")
endif ()

set(DISTRIB_DIR ${ROOT_PROJECT_DIR}/_distrib/lin_${QT_VERSION}_${DIR_PREFIX})

set(RUNTIME_OUTPUT_NAME ${PROJECT_NAME})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${DISTRIB_DIR}/bin)
set(LIB_DIRECTORY ${DISTRIB_DIR}/lib)
set(MOD_DIRECTORY ${DISTRIB_DIR}/modules)

