message("< Start of \"paths.cmake\"")

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(PROJECT_DIRECTORY ${CMAKE_SOURCE_DIR}/..)
set(SOURCE_DIRECTORY ${PROJECT_DIRECTORY}/sources)
set(CMAKE_DIRECTORY ${PROJECT_DIRECTORY}/_cmake)
set(INCLUDE_DIRECTORY ${PROJECT_DIRECTORY}/_include)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

# START OUTPUT BLOCK
message("CMAKE_SOURCE_DIR = ${CMAKE_SOURCE_DIR}")

message("PROJECT_DIRECTORY = ${PROJECT_DIRECTORY}")
message("SOURCE_DIRECTORY = ${SOURCE_DIRECTORY}")
message("CMAKE_DIRECTORY = ${CMAKE_DIRECTORY}")
message("INCLUDE_DIRECTORY = ${INCLUDE_DIRECTORY}")

message("CMAKE_ARCHIVE_OUTPUT_DIRECTORY = ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message("CMAKE_LIBRARY_OUTPUT_DIRECTORY = ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
message("CMAKE_RUNTIME_OUTPUT_DIRECTORY = ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

# END OUTPUT BLOCK

message("< End of file \"paths.cmake\"")
